# Generated by Django 4.2.7 on 2025-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotKnowledgeBase',
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
