# Generated by Django 4.2.7 on 2025-08-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='prevention_tip_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cybercrime',
            name='reporting_step_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
